
version: '3.7'

networks:
  default:
    external: true
    name: sagemaker-local

services:
  telegraf:
    image: telegraf:1.18-alpine
    volumes:
    - ./metrics/telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '127.0.0.1:8125:8125/udp'
    - '127.0.0.1:8092:8092/udp'

  influxdb:
    image: influxdb:1.8-alpine
    env_file: ./metrics/configuration.env
    ports:
      - '127.0.0.1:8886:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:10.4.2
    depends_on:
      - influxdb
    env_file: ./metrics/configuration.env
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./metrics/grafana/provisioning/:/etc/grafana/provisioning/

volumes:
  grafana_data: {}
  influxdb_data: {}
